default_stages: [pre-commit]
default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1 
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black-format
        args: ["--fast"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^todoforge/
  