"""Add. app_state table

Revision ID: a0d69ab9c208
Revises: c635c3d5cd1d
Create Date: 2025-02-10 10:53:10.875391

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0d69ab9c208"
down_revision: Union[str, None] = "c635c3d5cd1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_space_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_state")
    # ### end Alembic commands ###
